### ISSUE TITLE
NoSuchFieldError: impl_peer on Java 10

### ISSUE THREAD

**Issue by lsonnino** [Thizzer/jtouchbar#29] opened 2018-08-20 11:40 UTC
Hi, I get this error when running JTouchBar on Java 10 with JavaFX
```
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:473)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:372)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:941)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:973)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NoSuchFieldError: impl_peer
	at com.thizzer.jtouchbar.JTouchBarJNI.getJavaFXViewPointer0(Native Method)
	at com.thizzer.jtouchbar.javafx.JavaFXUtils.getViewPointer(JavaFXUtils.java:25)
	at com.thizzer.jtouchbar.JTouchBar$1.run(JTouchBar.java:81)
	at javafx.graphics/com.sun.glass.ui.Application.invokeAndWait(Application.java:466)
	at com.thizzer.jtouchbar.JTouchBar.show(JTouchBar.java:78)
	at gol.Main.start(Main.java:48)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:919)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(PlatformImpl.java:449)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Exception running application gol.Main
```
Thanks for your work, on Java 8 it still works fine
Cheers

**Comment by ttveldhuis** [comment] 2018-08-27 08:53
Closing. Duplicate of #27

**Closed as completed by ttveldhuis** 2018-08-27 08:53 UTC
Labels: duplicate
