### ISSUE TITLE
[Bug] Random crash

### ISSUE THREAD

**Issue by olivernybroe** [Thizzer/jtouchbar#26] opened 2018-04-20 12:58 UTC
A user had a random crash, but I have no idea what was being done and how to reproduce, I got the error log.
You can just close this issue if there aren't enough to go on, just thought I would report it as it might be obvious for you what went wrong. :) 

https://gist.github.com/olivernybroe/0b7f057cf30a49eba4a3035faee21b51

**Comment by ttveldhuis** [comment] 2018-04-20 15:18
Can't see from the error log if and at what point JTouchBar caused the memory error. But I will try to do some memory analysis.

**Comment by olivernybroe** [comment] 2018-05-02 13:37
Got a random crash again, might be related?
https://gist.github.com/olivernybroe/c54110439899a1c105f8fa0feb823bfe

**Comment by ttveldhuis** [comment] 2018-05-07 20:04
I found some places where local references should/could be deleted from memory sooner. Especially with the image loading this has an impact on the memory and can cause the crashes. Will fix it and commit as soon as possible.

**Comment by olivernybroe** [comment] 2018-05-07 21:14
That could be it. My system heavily uses image loading through byte arrays as I have the images ad Icon objects.

**Comment by ttveldhuis** [comment] 2018-08-27 12:11
Should be fixed in current 0.2.0 snapshot. Closing this now because unable to reproduce locally and plugin has been discontinued.

**Closed as completed by ttveldhuis** 2018-08-27 12:11 UTC
Labels: analysis
